# filename: auth-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: auth-server-internal
spec:
  type: ClusterIP
  selector:
    app: auth-server
  ports:
  - port: 80
    targetPort: 5000
