apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: judge0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: judge0/judge0:latest
          ports:
            - containerPort: 2358
          securityContext:
            privileged: true
          envFrom:
            - secretRef:
                name: judge0-env
      volumeMounts:
        - mountPath: /box
          name: box-volume
      volumes:
        - name: box-volume
          emptyDir: {}

