# filename: problem-ai-service-backend-config.yaml
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: problem-ai-service-backendconfig
spec:
  # Set a long timeout for potentially slow LLM responses
  timeoutSec: 300
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 15
    healthyThreshold: 1
    unhealthyThreshold: 2
    type: HTTP
    requestPath: /healthy
    port: 6000
