# we shouldnt use HPA for postgres in general, i just used it so it fits with the docker compose setup, i'm anyways storing it in a proper managed dtaabase CloudSQL/neondb (lets explore costs and see)

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: db-hpa
  namespace: judge0
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: db
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
