apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: judge0
spec:
  selector:
    app: db
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP  # Internal load-balancing between Postgres pods
